"""
Regenerate the four cross-variant LaTeX tables in results/tables/ from the
stdout logs of the four hybrid scripts (logs/{baseline,gated,forward,phys}.log)
plus the fig13_lcurve_phys.csv data file.

Tables regenerated:
  - table_per_material_by_variant.tex
  - table_ood_per_offset_by_variant.tex
  - table_cross_variant_comparison.tex
  - table_lcurve_phys_sweep.tex

Run after re-executing scripts/run_hybrid{,_gated,_forward,_phys}.py.

    python scripts/regenerate_tex_tables.py
"""

import os
import re
import pandas as pd

ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
LOGS_DIR = os.path.join(ROOT, "logs")
TABLES_DIR = os.path.join(ROOT, "results", "tables")
DATA_DIR = os.path.join(ROOT, "results", "data")

VARIANTS = ["baseline", "gated", "forward", "phys"]
MATERIALS_ORDER = [
    "water", "vegetation", "metal", "concrete",
    "soil", "asphalt", "human", "tree",
]


def parse_per_material(log_text):
    m = re.search(
        r"In-dist mean \|.T\|:\s*physics=([\d.]+) K\s+hybrid=([\d.]+) K",
        log_text,
    )
    agg = (float(m.group(1)), float(m.group(2))) if m else (None, None)
    per_mat = {}
    for mat in MATERIALS_ORDER:
        mm = re.search(rf"\b{mat}\s+([\d.]+)\s+([\d.]+)\s+\d+", log_text)
        if mm:
            per_mat[mat] = (float(mm.group(1)), float(mm.group(2)))
    return per_mat, agg


def parse_ood(log_text):
    rows = []
    for m in re.finditer(
        r"Offset \+(\d+) K:\s*physics \|.T\|=([\d.]+) K\s+hybrid \|.T\|=([\d.]+) K",
        log_text,
    ):
        rows.append((int(m.group(1)), float(m.group(2)), float(m.group(3))))
    return rows


def parse_kappa_pcts(log_text):
    out = {}
    for q in (10, 25, 50, 75, 90):
        m = re.search(rf"{q}th\s+([\d.]+)\s+([\d.]+)\s+[\d.]+", log_text)
        if m:
            out[q] = (float(m.group(1)), float(m.group(2)))
    return out


def parse_lipschitz_simple(log_text):
    """For baseline/gated/forward: 'Lipschitz upper bound: 1.0012'."""
    m = re.search(r"Lipschitz upper bound:\s*([\d.]+)", log_text)
    return float(m.group(1)) if m else None


def parse_lipschitz_phys(log_text, knee_lambda):
    """For phys: find the L-curve row for the knee lambda."""
    # Pattern: "Training at λ_phys = X ..." then "final_loss=... Lipschitz=Y ..."
    block_re = re.compile(
        r"Training at .*?phys = ([\d.eE+\-]+) \.\.\..*?Lipschitz=([\d.]+)",
        re.DOTALL,
    )
    for m in block_re.finditer(log_text):
        try:
            lam = float(m.group(1))
        except ValueError:
            continue
        if abs(lam - knee_lambda) < 1e-6 * max(abs(knee_lambda), 1.0):
            return float(m.group(2))
    return None


def load_logs(knee_lambda):
    parsed = {}
    for v in VARIANTS:
        with open(os.path.join(LOGS_DIR, f"{v}.log"), encoding="utf-8") as f:
            txt = f.read()
        per_mat, agg = parse_per_material(txt)
        parsed[v] = {
            "per_mat": per_mat,
            "agg": agg,
            "ood": parse_ood(txt),
            "kappa": parse_kappa_pcts(txt),
        }
        if v == "phys":
            parsed[v]["lipschitz"] = parse_lipschitz_phys(txt, knee_lambda)
        else:
            parsed[v]["lipschitz"] = parse_lipschitz_simple(txt)
    return parsed


# ------------------------------------------------------------------ tables --

def write_per_material_table(parsed, knee_lambda):
    rows = []
    for mat in MATERIALS_ORDER:
        phys = parsed["baseline"]["per_mat"][mat][0]
        hyb_vals = {v: parsed[v]["per_mat"][mat][1] for v in VARIANTS}
        best_v = min(hyb_vals, key=hyb_vals.get)
        cells = [f"{mat:<12}", f"{phys:.2f}"]
        for v in VARIANTS:
            val = hyb_vals[v]
            s = f"{val:.2f}"
            if val < phys:
                s = r"\underline{" + s + "}"
            if v == best_v:
                s = r"\textbf{" + s + "}"
            cells.append(s)
        rows.append(" & ".join(cells) + r" \\")

    phys_mean = parsed["baseline"]["agg"][0]
    hyb_means = {v: parsed[v]["agg"][1] for v in VARIANTS}
    best_v = min(hyb_means, key=hyb_means.get)
    mean_cells = [r"\emph{mean}", f"{phys_mean:.2f}"]
    for v in VARIANTS:
        val = hyb_means[v]
        s = f"{val:.2f}"
        if val < phys_mean:
            s = r"\underline{" + s + "}"
        if v == best_v:
            s = r"\textbf{" + s + "}"
        mean_cells.append(s)
    mean_row = " & ".join(mean_cells) + r" \\"

    knee_label = f"$\\lambda{{=}}{knee_lambda:g}$"
    tex = (
        "% Per-material in-distribution |dT| across all four hybrid variants\n"
        "% Auto-generated by scripts/regenerate_tex_tables.py\n"
        r"\begin{table}[t]" + "\n"
        r"  \centering" + "\n"
        r"  \begin{tabular}{lrrrrr}" + "\n"
        r"    \toprule" + "\n"
        r"    Material & Physics & Baseline & Gated & Forward & Phys (" + knee_label + r") \\" + "\n"
        r"    \midrule" + "\n"
        + "\n".join("    " + r for r in rows) + "\n"
        r"    \midrule" + "\n"
        f"    {mean_row}\n"
        r"    \bottomrule" + "\n"
        r"  \end{tabular}" + "\n"
        r"  \caption{Per-material mean $|\Delta T|$ on the 500-sample in-distribution test" + "\n"
        r"    set. Each material contributes 62--63 samples. Columns: physics-only TES" + "\n"
        r"    baseline; four hybrid variants. Bold entries indicate the best hybrid per" + "\n"
        r"    material; values better than the physics-only baseline are underlined.}" + "\n"
        r"  \label{tab:per-material-by-variant}" + "\n"
        r"\end{table}" + "\n"
    )
    path = os.path.join(TABLES_DIR, "table_per_material_by_variant.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(tex)
    return path


def write_ood_table(parsed, knee_lambda):
    offsets = [r[0] for r in parsed["baseline"]["ood"]]
    rows = []
    for i, off in enumerate(offsets):
        phys = parsed["baseline"]["ood"][i][1]
        hyb_vals = {v: parsed[v]["ood"][i][2] for v in VARIANTS}
        best_v = min(hyb_vals, key=hyb_vals.get)
        cells = [f"$+{off}$", f"{phys:.2f}"]
        for v in VARIANTS:
            val = hyb_vals[v]
            s = f"{val:.2f}"
            if val < phys:
                s = r"\underline{" + s + "}"
            if v == best_v:
                s = r"\textbf{" + s + "}"
            cells.append(s)
        rows.append(" & ".join(cells) + r" \\")

    knee_label = f"$\\lambda{{=}}{knee_lambda:g}$"
    tex = (
        "% OOD performance (mean |dT|) across temperature offset, all four hybrid variants\n"
        "% Auto-generated by scripts/regenerate_tex_tables.py\n"
        r"\begin{table}[t]" + "\n"
        r"  \centering" + "\n"
        r"  \begin{tabular}{rrrrrr}" + "\n"
        r"    \toprule" + "\n"
        r"    Offset (K) & Physics & Baseline & Gated & Forward & Phys (" + knee_label + r") \\" + "\n"
        r"    \midrule" + "\n"
        + "\n".join("    " + r for r in rows) + "\n"
        r"    \bottomrule" + "\n"
        r"  \end{tabular}" + "\n"
        r"  \caption{Out-of-distribution mean $|\Delta T|$ as a function of temperature" + "\n"
        r"    offset above the training range ($T_\text{train} \in [250, 380]$~K). Each" + "\n"
        r"    offset uses 100 samples cycled across 8 materials. Bold entries indicate" + "\n"
        r"    the best hybrid per row; underline indicates a hybrid better than" + "\n"
        r"    physics-only.}" + "\n"
        r"  \label{tab:ood-per-offset-by-variant}" + "\n"
        r"\end{table}" + "\n"
    )
    path = os.path.join(TABLES_DIR, "table_ood_per_offset_by_variant.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(tex)
    return path


def write_cross_variant_table(parsed, knee_lambda):
    def fmt_row(label, phys_val, var_vals, fmt="{:.2f}"):
        cells = [label]
        cells.append(fmt.format(phys_val) if phys_val is not None else "--")
        for v in VARIANTS:
            cells.append(fmt.format(var_vals[v]) if var_vals[v] is not None else "--")
        return " & ".join(cells) + r" \\"

    phys_mean = parsed["baseline"]["agg"][0]
    in_dist_var = {v: parsed[v]["agg"][1] for v in VARIANTS}
    improvement_var = {v: phys_mean - in_dist_var[v] for v in VARIANTS}
    ood_phys_0 = parsed["baseline"]["ood"][0][1]
    ood_phys_50 = parsed["baseline"]["ood"][-1][1]
    ood_var_0 = {v: parsed[v]["ood"][0][2] for v in VARIANTS}
    ood_var_50 = {v: parsed[v]["ood"][-1][2] for v in VARIANTS}
    better_var = {
        v: all(parsed[v]["ood"][i][2] < parsed[v]["ood"][i][1]
               for i in range(len(parsed[v]["ood"])))
        for v in VARIANTS
    }
    kap_p50_phys = parsed["baseline"]["kappa"][50][0]
    kap_p90_phys = parsed["baseline"]["kappa"][90][0]
    kap_p50_var = {v: parsed[v]["kappa"][50][1] for v in VARIANTS}
    kap_p90_var = {v: parsed[v]["kappa"][90][1] for v in VARIANTS}
    lip_var = {v: parsed[v]["lipschitz"] for v in VARIANTS}

    rows = []
    rows.append(fmt_row(r"In-dist mean $|\Delta T|$ (K)", phys_mean, in_dist_var))
    rows.append(fmt_row(r"Improvement over physics", None, improvement_var, fmt="{:+.2f}"))
    rows.append(fmt_row(r"OOD $+0$~K", ood_phys_0, ood_var_0))
    rows.append(fmt_row(r"OOD $+50$~K", ood_phys_50, ood_var_50))
    yesno_cells = [r"Better than physics at every OOD offset?", "--"]
    for v in VARIANTS:
        yesno_cells.append("yes" if better_var[v] else "no")
    rows.append(" & ".join(yesno_cells) + r" \\")
    rows.append(fmt_row(r"$\kappa_\text{hybrid}$ p50", kap_p50_phys, kap_p50_var))
    rows.append(fmt_row(r"$\kappa_\text{hybrid}$ p90", kap_p90_phys, kap_p90_var, fmt="{:.1f}"))
    rows.append(fmt_row(r"Lipschitz upper bound", None, lip_var, fmt="{:.3f}"))

    knee_label = f"$\\lambda{{=}}{knee_lambda:g}$"
    tex = (
        "% Cross-variant comparison table\n"
        "% Auto-generated by scripts/regenerate_tex_tables.py\n"
        r"\begin{table}[t]" + "\n"
        r"  \centering" + "\n"
        r"  \begin{tabular}{lrrrrr}" + "\n"
        r"    \toprule" + "\n"
        r"    Metric & Physics & Baseline & Gated & Forward & Phys (" + knee_label + r") \\" + "\n"
        r"    \midrule" + "\n"
        + "\n".join("    " + r for r in rows) + "\n"
        r"    \bottomrule" + "\n"
        r"  \end{tabular}" + "\n"
        r"  \caption{Cross-variant comparison of the four hybrid variants against the" + "\n"
        r"    physics-only baseline. In-distribution accuracy is the aggregate mean" + "\n"
        r"    over the 500-sample test set.}" + "\n"
        r"  \label{tab:cross-variant-comparison}" + "\n"
        r"\end{table}" + "\n"
    )
    path = os.path.join(TABLES_DIR, "table_cross_variant_comparison.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(tex)
    return path


def write_lcurve_table():
    """L-curve table — prefers the multi-seed summary if available."""
    summary_path = os.path.join(DATA_DIR, "fig13_lcurve_phys_summary.csv")
    multi_path = os.path.join(DATA_DIR, "fig13_lcurve_phys_multiseed.csv")

    if os.path.exists(summary_path) and os.path.exists(multi_path):
        s = pd.read_csv(summary_path).sort_values("lambda_phys")
        m = pd.read_csv(multi_path)
        n_seeds = m["seed"].nunique()
        rows = []
        for _, r in s.iterrows():
            lam = r["lambda_phys"]
            acc_med = r["accuracy_median"]
            acc_p25 = r["accuracy_p25"]
            acc_p75 = r["accuracy_p75"]
            v_med = r["violation_median"]
            v_p25 = r["violation_p25"]
            v_p75 = r["violation_p75"]
            lip_med = r["lipschitz_median"]
            knee = bool(r["is_knee_median"])
            lam_str = f"{lam:g}"
            acc_str = f"{acc_med:.2f} [{acc_p25:.2f}, {acc_p75:.2f}]"
            viol_str = f"{v_med:.2e} [{v_p25:.2e}, {v_p75:.2e}]"
            lip_str = f"{lip_med:.3f}"
            if knee:
                lam_str = f"\\textbf{{{lam_str} (knee)}}"
                acc_str = f"\\textbf{{{acc_str}}}"
                viol_str = f"\\textbf{{{viol_str}}}"
                lip_str = f"\\textbf{{{lip_str}}}"
            rows.append(f"{lam_str} & {acc_str} & {viol_str} & {lip_str} \\\\")

        tex = (
            "% Multi-seed L-curve sweep over lambda_phys (Hansen 1992 on median curve)\n"
            "% Auto-generated by scripts/regenerate_tex_tables.py\n"
            r"\begin{table}[t]" + "\n"
            r"  \centering" + "\n"
            r"  \begin{tabular}{rlll}" + "\n"
            r"    \toprule" + "\n"
            r"    $\lambda_\text{phys}$ & accuracy $|\Delta T|$ (K) & phys violation & Lipschitz UB \\" + "\n"
            r"    \midrule" + "\n"
            + "\n".join("    " + r for r in rows) + "\n"
            r"    \bottomrule" + "\n"
            r"  \end{tabular}" + "\n"
            r"  \caption{Multi-seed L-curve sweep over $\lambda_\text{phys}$ for the" + "\n"
            f"    physics-consistency variant ({n_seeds} model-init seeds, training and " + "\n"
            r"    test data fixed). Accuracy $|\Delta T|$ and physics-violation are" + "\n"
            r"    reported as median [p25, p75] across seeds. Hansen's corner-distance" + "\n"
            r"    heuristic on the median curve selects the bold-marked row.}" + "\n"
            r"  \label{tab:lcurve-phys-sweep}" + "\n"
            r"\end{table}" + "\n"
        )
        path = os.path.join(TABLES_DIR, "table_lcurve_phys_sweep.tex")
        with open(path, "w", encoding="utf-8") as f:
            f.write(tex)
        return path

    # --- single-seed fallback (original behaviour) ---
    df = pd.read_csv(os.path.join(DATA_DIR, "fig13_lcurve_phys.csv"))
    log = open(os.path.join(LOGS_DIR, "phys.log"), encoding="utf-8").read()
    lip_by_lambda = {}
    block_re = re.compile(
        r"Training at .*?phys = ([\d.eE+\-]+) \.\.\..*?Lipschitz=([\d.]+)",
        re.DOTALL,
    )
    for m in block_re.finditer(log):
        try:
            lip_by_lambda[float(m.group(1))] = float(m.group(2))
        except ValueError:
            pass

    rows = []
    for _, r in df.iterrows():
        lam = r["lambda_phys"]
        acc = r["accuracy_T_mae"]
        viol = r["phys_violation"]
        knee = bool(r["is_knee"])
        lip = lip_by_lambda.get(lam, None)
        lam_str = f"{lam:g}"
        if knee:
            lam_str = f"\\textbf{{{lam_str} (knee)}}"
            acc_str = f"\\textbf{{{acc:.2f}}}"
            viol_str = f"\\textbf{{{viol:.2e}}}"
            lip_str = f"\\textbf{{{lip:.3f}}}" if lip is not None else "--"
        else:
            acc_str = f"{acc:.2f}"
            viol_str = f"{viol:.2e}"
            lip_str = f"{lip:.3f}" if lip is not None else "--"
        rows.append(f"{lam_str} & {acc_str} & {viol_str} & {lip_str} \\\\")

    tex = (
        "% L-curve sweep over lambda_phys (Hansen 1992 corner-distance heuristic)\n"
        "% Auto-generated by scripts/regenerate_tex_tables.py\n"
        r"\begin{table}[t]" + "\n"
        r"  \centering" + "\n"
        r"  \begin{tabular}{rrrr}" + "\n"
        r"    \toprule" + "\n"
        r"    $\lambda_\text{phys}$ & accuracy $|\Delta T|$ (K) & phys violation & Lipschitz UB \\" + "\n"
        r"    \midrule" + "\n"
        + "\n".join("    " + r for r in rows) + "\n"
        r"    \bottomrule" + "\n"
        r"  \end{tabular}" + "\n"
        r"  \caption{L-curve sweep over $\lambda_\text{phys}$ for the physics-consistency" + "\n"
        r"    variant. Accuracy $|\Delta T|$ is the mean in-distribution error;" + "\n"
        r"    phys-violation is the mean relative forward-model residual" + "\n"
        r"    $\|L - P(\hat x)\|^2 / \|L\|^2$. Hansen's corner-distance heuristic" + "\n"
        r"    selects the bold-marked row.}" + "\n"
        r"  \label{tab:lcurve-phys-sweep}" + "\n"
        r"\end{table}" + "\n"
    )
    path = os.path.join(TABLES_DIR, "table_lcurve_phys_sweep.tex")
    with open(path, "w", encoding="utf-8") as f:
        f.write(tex)
    return path


def main():
    # Prefer the multi-seed summary if present; else fall back to the
    # single-seed fig13 CSV. Single source of truth for knee selection.
    summary_path = os.path.join(DATA_DIR, "fig13_lcurve_phys_summary.csv")
    if os.path.exists(summary_path):
        df_sum = pd.read_csv(summary_path)
        knee_row = df_sum[df_sum["is_knee_median"]].iloc[0]
        knee_lambda = float(knee_row["lambda_phys"])
        print(f"Knee lambda (from multi-seed median): {knee_lambda:g}")
    else:
        df13 = pd.read_csv(os.path.join(DATA_DIR, "fig13_lcurve_phys.csv"))
        knee_row = df13[df13["is_knee"]].iloc[0]
        knee_lambda = float(knee_row["lambda_phys"])
        print(f"Knee lambda (single-seed fallback): {knee_lambda:g}")

    parsed = load_logs(knee_lambda)
    for v in VARIANTS:
        p = parsed[v]
        print(f"\n[{v}] agg={p['agg']}, lipschitz={p['lipschitz']}")
        print(f"  per_mat: {p['per_mat']}")
        print(f"  ood: {p['ood']}")
        print(f"  kappa: {p['kappa']}")

    print()
    for fn, args in [
        (write_per_material_table, (parsed, knee_lambda)),
        (write_ood_table, (parsed, knee_lambda)),
        (write_cross_variant_table, (parsed, knee_lambda)),
        (write_lcurve_table, ()),
    ]:
        path = fn(*args)
        print("Wrote", path)


if __name__ == "__main__":
    main()
